spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APP_NAME}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: quantity-service
              uri: ${CONVERSION_SERVICE_URL:lb://quantity-measurement-service}
              predicates:
                - Path=/quantity/**
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:lb://auth-service}
              predicates:
                - Path=/auth/**

server:
  port: ${PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
